### ISSUE TITLE
Google Drive integration for Group work

### ISSUE THREAD

**Issue by moo00se** [igorski/bitmappery#16]
Would this be able to be integrated with a Google Drive so multiple people could work on one file? I really dig the simplicity of this app.

**Comment by igorski** [comment]
Hi @moo00se nice to hear the application is of use to you.

Google Drive implementation had been on the backlog for a while, so let's treat this issue as the official "ticket" to monitor the implementation progress. Ideally, BitMappery should reuse the UI used by the Dropbox implementation, only using a different storage API under the hood.

**Comment by moo00se** [comment]
Hi @igorski 

My apologies on the delay. Works great in my testing. I will implement somethings and deploy it to my team and give you feedback then. Thank you!

**Comment by igorski** [comment]
Closing this as it has been in production for a while. Any new feedback requests related to Google Drive integration may be posted in a new issue :)
