### ISSUE TITLE
Docker container?

### ISSUE THREAD

**Issue by philipdistefano** [igorski/bitmappery#18]
This project looks sweet!  Any plans for a docker container?

**Comment by igorski** [comment]
Hi @philipdistefano thanks for the kind comment.

I hadn't planned a Docker container, maybe I'm overlooking your use case, but what benefit would the container provide ? Is it to run a self hosted BitMappery version ? BitMappery supports Service Workers and can be installed to the homescreen, which should make it a standalone app.

But once more, maybe I'm overlooking the benefit you see ? :)

**Comment by philipdistefano** [comment]
@igorski Yes, exactly!  I have the project up and running, but docker would be much easier for most people, and then easier to maintain.

**Comment by Ange-Cesari** [comment]
@philipdistefano 
Hey,

I wrote a minimalist dockerfile to run bitmappery via docker container.

Simply follow these steps to generate the image yourself: 

pre-requesite : docker & git 

Step 1 : Go into a folder on your local machine and git clone le projet BitMappery : 
```bash
git clone https://github.com/igorski/bitmappery.git
```

Step 2 : Create a dockerfile at the root folder of the project and paste the following code : 

```dockerfile
# Written by Ange Cesari
# Use official Node.js based on Alpine
FROM node:16-alpine

# Install Yarn
RUN apk add --no-cache yarn

# Create dir for application
WORKDIR /usr/src/app

# Copy package.json
COPY package.json ./

# Install dependencies
RUN yarn install

# Copy the rest of the application code
COPY . .

# Expose the port the application will run on
EXPOSE 5173

# Run the application
CMD ["yarn", "dev", "--host", "0.0.0.0"]
```

Steo 3 : Build the image : 
```bash
docker build -t bitmappery .
```

Step 4 : Once i'ts built, run the container and bind the ports :
```bash
docker run -d -p 5173:5173 --name bitmappery-container bitmappery
```

Step 5 : Once the container is started, you should be able to reach `http://localhost:5173`

**Comment by igorski** [comment]
Alright, following this again since there is more traction on the topic.

Thanks @Ange-Cesari for your example Dockerfile. We could add this to the repository. Maybe @philipdistefano you have some additional input ?

**Comment by philipdistefano** [comment]
I haven't had a chance to test it yet, but it's rad to see this getting some traction!  Will take a look later this week.  Thanks @Ange-Cesari !

**Comment by philipdistefano** [comment]
@Ange-Cesari @igorski Working successfully!  Thanks for doing that!

**Comment by igorski** [comment]
Thanks for the verification @philipdistefano 

@Ange-Cesari I could add the Dockerfile to the repository with an addendum in the README on how to start it, or you could make a pull request containing the same, which I can then merge (if you care about having a contributor entry in the project :) ).

**Comment by Ange-Cesari** [comment]
@igorski 

I did the PR #28 
I especially did not do a new branch so that you can merge easily, as no code has been edited. Obviously if code was edited/added/remove I would have done a new branch.

Hope it solves the issue and happy to contribute :).

**Comment by igorski** [comment]
Awesome, thanks for the effort! I'll have a look at your other suggestions and see how this self hosting thing can be enriched in iterations to come :)

**Comment by tiritibambix** [comment]
Hello.

I was willing to try your project as it looks really cool.
I followed instructions [here](https://github.com/igorski/bitmappery#docker-based-self-hosted-version) but I encountered several warnings and one error:
```
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  5.021MB
Step 1/8 : FROM node:18-alpine
18-alpine: Pulling from library/node
38a8310d387e: Already exists
1b970ccead88: Pull complete
e27d76322248: Pull complete
fdd316e9b466: Pull complete
Digest: sha256:6eb9c3d9bd191bd2cc6ce7ec3d5ec4c2127616140c8586af96a6bec8f28689d1
Status: Downloaded newer image for node:18-alpine
 ---> e907c843e7bd
Step 2/8 : RUN apk add --no-cache yarn
 ---> Running in e3fa1abe8c8a
fetch https://dl-cdn.alpinelinux.org/alpine/v3.21/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.21/community/x86_64/APKINDEX.tar.gz
(1/12) Installing ca-certificates (20241010-r0)
(2/12) Installing ada-libs (2.9.2-r1)
(3/12) Installing brotli-libs (1.1.0-r2)
(4/12) Installing c-ares (1.34.3-r0)
(5/12) Installing icu-data-en (74.2-r0)
Executing icu-data-en-74.2-r0.post-install
*
* If you need ICU with non-English locales and legacy charset support, install
* package icu-data-full.
*
(6/12) Installing icu-libs (74.2-r0)
(7/12) Installing nghttp2-libs (1.64.0-r0)
(8/12) Installing simdjson (3.10.1-r0)
(9/12) Installing simdutf (5.6.3-r0)
(10/12) Installing sqlite-libs (3.47.1-r0)
(11/12) Installing nodejs (22.11.0-r0)
(12/12) Installing yarn (1.22.22-r1)
Executing busybox-1.37.0-r8.trigger
Executing ca-certificates-20241010-r0.trigger
OK: 73 MiB in 29 packages
 ---> Removed intermediate container e3fa1abe8c8a
 ---> 336baeb912d2
Step 3/8 : WORKDIR /usr/src/app
 ---> Running in c9f64f8abdd7
 ---> Removed intermediate container c9f64f8abdd7
 ---> 4173698cff45
Step 4/8 : COPY package.json ./
 ---> 37537d476e42
Step 5/8 : RUN yarn install
 ---> Running in 4782b8b19169
yarn install v1.22.22
info No lockfile found.
[1/4] Resolving packages...
warning eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
warning eslint > @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
warning eslint > @humanwhocodes/config-array > @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
warning eslint > file-entry-cache > flat-cache > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning eslint > file-entry-cache > flat-cache > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning eslint > file-entry-cache > flat-cache > rimraf > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
warning v-tooltip > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning vue@2.7.16: Vue 2 has reached EOL and is no longer actively maintained. See https://v2.vuejs.org/eol/ for more details.
[2/4] Fetching packages...
error pdfjs-dist@4.9.155: The engine "node" is incompatible with this module. Expected version ">=20". Got "18.20.5"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn install' returned a non-zero code: 1
```

Not being a programmer and having limit docker knowledge, I fear I can't debug this myself and offer help.

I hope you can understand this better than I do.
