### ISSUE TITLE
any support for pdf?

### ISSUE THREAD

**Issue by aliwebnapp** [igorski/bitmappery#19]

**Comment by igorski** [comment]
Currently no, but it's a good candidate to add!

What would your ideal use case for using PDF be ? Import/export of PDF documents as layered images or also to include editable text ? The reason I ask about text is that it adds additional complexity to parsing/writing the format (which shouldn't be bad), but presents a problem where BitMappery uses Google Fonts, which can't be embedded in a PDF doc.

**Comment by igorski** [comment]
Initial support for importing PDF documents (where pages are imported as rasterized images) will be added in https://github.com/igorski/bitmappery/pull/26

**Comment by igorski** [comment]
PFD import has been added in f16c7492e928bc2376139d556611f8d3a559c774
