### ISSUE TITLE
Upon adding layer mask, the brush/eraser are permanently in masking mode for that layer

### ISSUE THREAD

**Issue by dentistformyeye** [igorski/bitmappery#8]
1. Start with a new document. Switch to the brush tool. Draw a square.
2. Add a layer mask. Attempt to make a side of the square thicker.
3. Click the mask icon. The layer name should turn black. Attempt to mask a visible side of the square.
4. Click the layer name. The layer name should turn white. Attempt to make a visible side of the square thicker.

In steps 2 and 4, the brush masks the original drawing instead of adding on to it.
Workaround: to draw normally, create another layer that doesn't have a mask.

**Comment by igorski** [comment]
Addressed in 8d8a997eafd12bcb1c7da9807506f228510fd195 (pending deployment)

**Comment by igorski** [comment]
Deployed onto production server.
