### ISSUE TITLE
What Open Source License is this software under?

### ISSUE THREAD

**Issue by timmwille** [igorski/bitmappery#9]
I'm currently listing Open Source Tools on different project sites but I'm not sure if this is really the case here? I could not find a license file, but would like to include this tool. Where can I find the info?

**Comment by igorski** [comment]
Hi there Timm, nice to hear you want to include Bitmappery on your listing!
I had completely missed to add the LICENSE file to this repository. I have added the license in commit 6619374c27395b0c6e730b2bf8b5123768f5175d

**Comment by igorski** [comment]
@timmwille if there are no further questions on this topic, I will close this issue if you agree.

**Comment by timmwille** [comment]
> @timmwille if there are no further questions on this topic, I will close this issue if you agree.

sorry I missed the good news, thank you → all clear now :100: :+1:
